### ISSUE TITLE
For users with ENTSO-E apikey - should we replace sahkotin integration with ENTSO-E data ? 

### ISSUE THREAD

**Issue by oh4kpn** [vividfog/nordpool-predict-fi#16]
sahkotin-api was quite slow today and thought about using ENTSO-E integration to replace it

**Comment by oh4kpn** [comment]
https://github.com/EnergieID/entsoe-py might be worth looking

**Comment by pkautio** [comment]
Entsoe-py is already used to fetch nuclear production forecast. Fetching price info too is easy. I will add necessary code during weekend.

**Comment by vividfog** [comment]
Sähkötin has been working fine for a long time now, so I think we'll stick to that.
