### ISSUE TITLE
Add additional costs (such as transfer fees) to the prediction

### ISSUE THREAD

**Issue by herrar1** [vividfog/nordpool-predict-fi#19]
Add additional costs (such as transfer fees) to the prediction. So that it isn't as confusing as it is now. To color match today's real values and tomorrows prediction in Home Assistant... in my case i have around 5.39 cents of additional costs so that the prediction and real values don't match.
![image](https://github.com/vividfog/nordpool-predict-fi/assets/117488172/849b300b-a7c1-41a8-8413-479b90225ab4)

**Comment by vividfog** [comment]
Transfer fees vary per location, so this isn't something that can be calculated up front for all. You can achieve this by editing the .yaml source that draws the graph, by adding a formula to the values before printing them out. For example "value + X cents" if your transfer fee is a fixed value.

This would add 10 cents to the value:

`return [parseInt(timestamp) - 7200000, value + 10];`

Hope this helps.
