### ISSUE TITLE
VAT incorrect

### ISSUE THREAD

**Issue by Hirsipilari** [vividfog/nordpool-predict-fi#22]
Since September 2024, the VAT changed in Finland from 24% to 25.5%.

**Comment by vividfog** [comment]
We fetch Sähkötin prices with VAT (api_url = "https://sahkotin.fi/prices?vat") and 25.5 is factored into the data on arrival.

I found VAT24 in the Home Assistant YAML template samples, where the multiplier should be 125.5 and not 124. That'll need a fix in the YAML and README.

Is there some other place that needs an update?

**Comment by Hirsipilari** [comment]
YAML and readme were the ones I spotted where the 124 multiplier was mentioned. I just wanted to point this out so it wouldn't be confusing to anyone :)
