### ISSUE TITLE
Foreca → FMI API

### ISSUE THREAD

**Issue by T3m3z** [vividfog/nordpool-predict-fi#3]
Hello!

What an interesting project! Just to let you know that Foreca's Wind Forecasts are available through this API which might make this project "a bit less fragile": https://www.foreca.fi/api/wind-power?id=100658225

Mandatory disclaimer: I don't know whether it is OK to use that API directly without a contract/agreement with Foreca and cannot take any responsibility of any problems between you and Foreca caused by a possible usage of this publicly accessible API :)

Best Regards,
T3m3z

**Comment by vividfog** [comment]
This would be interesting but could indeed introduce fragility of another kind. Their public "Sähköpuntari" is made for consumers it says, to help make estimates about spot prices. But Foreca enterprise API intro talks about a 30 day free trial. Key or not, it's not clear how open this API is meant to be. And this is not an enterprise, it'a a hobby. Perhaps the intent of this API becomes clear in time.

**Comment by T3m3z** [comment]
Accessing "Sähkön hintapuntari" page loads data from https://www.foreca.fi/api/wind-power?id=100658225 (id is used to show temperature data for a certain place, 100658225 is Helsinki). I believe that you are "parsing" SVG that is is created inside browser from the data provided by https://www.foreca.fi/api/wind-power?id=100658225 . But I see your point.

**Comment by vividfog** [comment]
I checked from Foreca. The wind power forecast is for personal use only. I can't serve a page where this data is used, whether via API or otherwise. Plan B will go into effect as soon as I can get the code changes done. Which is soon. Unfortunately I don't have time to start a longer discussion with data owners to make things otherwise. This Winter vacation is not long enough for that.

**Comment by T3m3z** [comment]
Alright!

How about loading windspeedms and temperature forecast from FMI from some carefully selected locations and then

Example temperature and wind speed forecast for the following days to Helsinki:
https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::forecast::edited::weather::scandinavia::point::simple&place=helsinki&timestep=60&parameters=temperature,windspeedms&starttime=2024-02-28T18:00:00Z&endtime=2024-03-09T00:00:00Z

Fingrid has also open data API for historical wind power production (https://data.fingrid.fi/datasets/75) and maximum wind power capacity (https://data.fingrid.fi/datasets/268). Maybe one option would be to train a model to predict wind power generation from wind speeds obtained from FMI open data API and wind power output from Fingrid. And then use previously mentioned FMI API to get forecast of windpower for the following days?

**Comment by T3m3z** [comment]
Yeah, makes sense. But anyway, just wanted to point to this FMI open data API which could be used to load wind forecasts. 

Most of the wind farms are on west coast so maybe getting some wind forecasts from carefully selected locations along the coast would give better results than wind forecast of Tampere Airport. Maybe some analysis on wind farm locations would be optimal points. https://tuulivoimayhdistys.fi/en/wind-power-in-finland/map

**Comment by T3m3z** [comment]
Anyway, I will close this "issue" as it was meant for discussion of possible APIs/data sources and most probably won't bring any extra value now. Thank you for creating this inspiring project!

**Comment by vividfog** [comment]
I don't mind if it stays open. Something like "X most representative spots in Finland" could work. And that's indeed the low-hanging option to try next. Tampere wasn't there to predict wind farm performance. It was an indirect (a very indirect) signal of heating power requirements. Using multiple inland and coastal locations might work.

**Comment by janneho** [comment]
Fingrid has [tuulivoimaennuste](https://www.fingrid.fi/sahkomarkkinainformaatio/tuulivoiman-tuotanto/), Is this something that can be used instead of foreca?

**Comment by vividfog** [comment]
It was quite an effort to decipher the FMI API to something I can grab into a dataframe, but I think this might work. Two functions.

1. `get_forecast` for a place and day
2. `get_history` for a place and day

One to populate the training database, and the other to run inference.

What I'm not entirely happy about is that the parameter names space for history vs forecast don't seem to match in the API. But these are the closest two I could find, and value-wise they seem to correlate closely but not perfectly. Guess the weather forecast isn't always perfect.

If you are aware of better parameter values or stored queries to use for this purpose, I'm all ears.

https://github.com/vividfog/nordpool-predict-fi/blob/plan_b/util/fmi.py

Just run that .py file. It ends with a main function:

```
# Example usage
date = "2024-02-28"
place = "Helsinki"

# Get forecast for a specific day
parameters_forecast = ['temperature', 'windspeedms']
forecast = get_forecast(place, date, parameters_forecast)
print("Forecast:")
print(forecast)

# Get history for a specific day
parameters_history = ['TA_PT1H_AVG', 'WS_PT1H_AVG']
history = get_history(place, date, parameters_history)
print("\nHistory:")
print(history)

```

The idea is to use these for a set of wind park clusters points/areas for wind speed (predictor for wind power vs price), and a set of population centers for temperature (predictor for heating energy consumption vs price). Yes, it would be even nicer to build a proper "wind power forecast model", but ensemble modeling may be a later evolution, if needed.

**Comment by vividfog** [comment]
> Fingrid has [tuulivoimaennuste](https://www.fingrid.fi/sahkomarkkinainformaatio/tuulivoiman-tuotanto/), Is this something that can be used instead of foreca?

Fingrid API only forecasts 2 days. That would be a bit short, if the goal is about 5 days.

**Comment by T3m3z** [comment]
> If you are aware of better parameter values or stored queries to use for this purpose, I'm all ears.

I have encountered 3 different stored queries for forecast data. There is a stored query for ECMWF and HARMONIE models but their forecast length is something like 54 hours. So not really usable in this case. I have used them to forecast my house heating needs based on upcoming weather conditions and for that purpose HARMONIE model has been sufficient. I just happened to notice that they have published "forecast done by meteorologist" which was the stored query shown in my initial example. For some reason it has a lot longer timespan (making it usable in this project) and might also contain some "extra human intuition" baked in to the data provided by the models. So based on my current knowledge that is the best one available as open data.

![image](https://github.com/vividfog/nordpool-predict-fi/assets/6449536/9e8b14df-02b7-44fa-b9bc-a88072aade5f)

More info about datasets can be found from here (in Finnish): https://www.ilmatieteenlaitos.fi/avoin-data-avattavat-aineistot

It is possible to load data using latlon too. MIght be useful if you decide to divide Finland into grid of for example 200km x 200km for wind forecasts:
https://opendata.fmi.fi/wfs?service=WFS&version=2.0.0&request=getFeature&storedquery_id=fmi::forecast::edited::weather::scandinavia::point::simple&latlon=61.1,21&latlon=60.1,19.9&parameters=windspeedms

And there are multiple "wind parameters" available (depending on the model). For example for fmi::forecast::edited::weather::scandinavia::point::simple there seems to be the following available:
WindDirection
WindSpeedMS
WindVectorMS
WindUMS
WindVMS

"Statistics Finland" seems to have data about population density available if it helps determining "best places to get temperature data": https://www.stat.fi/org/avoindata/paikkatietoaineistot/vaestoruutuaineisto_1km_en.html

I tried to find open data for analyzing locations of wind farms but could not directly find any (well I used like 5 mins last night before going to bed). Foreca API seems to have that data: https://www.foreca.fi/api/wind-power?id=100658225 . List of operating and dismantled wind farms can be found from here in excel format: https://tuulivoimayhdistys.fi/en/wind-power-in-finland/wind-power-in-production-and-dismantled

Maybe the selection of from which places to get temperature data would be just to get 1 or 2 largest cities from every major area (like Uusimaa/Pohjois-Karjala/etc) and feed their data to the model. Not sure if it would add too many parameters to the model and make harder for the model to learn individual factors affecting price. Or maybe just selecting biggest cities from this list: https://fi.wikipedia.org/wiki/Luettelo_Suomen_kunnista_v%C3%A4kiluvun_mukaan Something like Helsinki, Tampere, Oulu, Joensuu, Turku, Jyväskylä, Rovaniemi. Maybe those would already give the model the ability to learn how power consumption of different geographical areas (for example like Joensuu for eastern finland Joensuu) affect price levels.

**Comment by Routout** [comment]
How about using yr.no wind forecast data?
https://developer.yr.no/doc/TermsOfService/

**Comment by vividfog** [comment]
To test something end to end and evaluate, I'm running with this set:

```
# Kalajoki, Kaskinen, Kemi, Pori FMI weather stations represent wind power clusters
FMISID_WS="101673,101256,101846,101267"

# Oulu, Pirkkala, Vantaa, Jyväskylä weather stations represent urban clusters
FMISID_T="101786,101118,100968,101339"
```

I'm using FMISIDs instead of place names or coordinates, because those are the FMI epicenters for observations and forecasts. That is, the weather observations and weather forecast have a relatively direct correlation. I hypothesize that using a bbox or other interpolated observations/forecasts would produce more noise into the training data.

With this approach, the model is not as strong as with Foreca's much more comprehensive 10-day wind power forecast that takes into account dozens of sites individually. But that's not data this project has access to. I'll push forward with this and look at the plots.

It looks like mean average error will go from 1 cent to about 2 cents. And the mean error in larger variations about doubles as well. R2 goes from .9 to .8. Could be worse. The plots will tell, how the model feels like after that.

It's easy to add more or fewer weather stations to the pipeline via .env.local. Whether 4+4 is the right number or not, time will tell.

**Comment by savikko** [comment]
Posted to Älykoti -fb group also, but I think this is more relevant address :)

So, it is possible to fetch all wind turbines in Finland (in production) from https://services-eu1.arcgis.com/2H9jvPu9mBpcAH9F/arcgis/rest/services/Web_Map_2024_February_WFL1/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&resultOffset=0&resultRecordCount=1000&cacheHint=true&quantizationParameters=%7B%22mode%22%3A%22edit%22%7D

It will return features -array, where one item might be like this:
```json
{
	"attributes": {
		"OBJECTID": 1,
		"Municipality___Name": "Alavieska, Kytölä",
		"Region": "North Ostrobothnia",
		"Phase__FI_": "Tuotannossa",
		"Phase__EN_": "In Production",
		"Year": "2015",
		"Total_MW_min": "19",
		"Total_MW_max": 20,
		"Turbines_min": 6,
		"Turbines_max": 6,
		"Turbine_tip_height__m_": null,
		"Turbine_hub_height__m_": "137",
		"Turbine_Rotor_Diameter__m_": "126",
		"Manufacturer": "Vestas V126",
		"Owner_Developer": "Kytölän Tuulipuisto Ky",
		"Www": "https://www.taalerivarainhoito.com/application/files/9715/6145/0475/Taaleri_Tuulitehdas_II_vuosiraportti_2017.pdf",
		"Onshore": "Yes",
		"Y_D": 64.25341,
		"X_D": 24.22742,
		"Updated": 1612137600000
	}
}
```

So. including latlon (`Y_D / X_D`) and total power (`Total_MW_max`).

Then, grouping data with some sensible areas (lets say 100km x 100km) and then getting wind forecast for those from e.g. yr.no/met.no and then having some wind speed/power percentage lookup table we might get quite good estimation of wind power for each hour.

Not a clue if this would work but just as an idea.

Data itself looks like free to use (ref https://www.arcgis.com/home/item.html?id=b7befefe269b4932a37160a1fea26640). Seems that there is also monthly updates to the list (when listing features by author).

**Comment by vividfog** [comment]
We're back online here: https://nordpool-predict-fi.web.app

I haven't committed or merged everything yet. This will become part of "main" perhaps later today. The main URL goes online when everything seems to be stable for a while.

**Comment by vividfog** [comment]
> Posted to Älykoti -fb group also, but I think this is more relevant address :)
> 
> So, it is possible to fetch all wind turbines in Finland (in production) from https://services-eu1.arcgis.com/2H9jvPu9mBpcAH9F/arcgis/rest/services/Web_Map_2024_February_WFL1/FeatureServer/0/query?f=json&where=1%3D1&returnGeometry=false&spatialRel=esriSpatialRelIntersects&outFields=*&resultOffset=0&resultRecordCount=1000&cacheHint=true&quantizationParameters=%7B%22mode%22%3A%22edit%22%7D
> 
> It will return features -array, where one item might be like this:
> 
> ```json
> {
> 	"attributes": {
> 		"OBJECTID": 1,
> 		"Municipality___Name": "Alavieska, Kytölä",
> 		"Region": "North Ostrobothnia",
> 		"Phase__FI_": "Tuotannossa",
> 		"Phase__EN_": "In Production",
> 		"Year": "2015",
> 		"Total_MW_min": "19",
> 		"Total_MW_max": 20,
> 		"Turbines_min": 6,
> 		"Turbines_max": 6,
> 		"Turbine_tip_height__m_": null,
> 		"Turbine_hub_height__m_": "137",
> 		"Turbine_Rotor_Diameter__m_": "126",
> 		"Manufacturer": "Vestas V126",
> 		"Owner_Developer": "Kytölän Tuulipuisto Ky",
> 		"Www": "https://www.taalerivarainhoito.com/application/files/9715/6145/0475/Taaleri_Tuulitehdas_II_vuosiraportti_2017.pdf",
> 		"Onshore": "Yes",
> 		"Y_D": 64.25341,
> 		"X_D": 24.22742,
> 		"Updated": 1612137600000
> 	}
> }
> ```
> 
> So. including latlon (`Y_D / X_D`) and total power (`Total_MW_max`).
> 
> Then, grouping data with some sensible areas (lets say 100km x 100km) and then getting wind forecast for those from e.g. yr.no/met.no and then having some wind speed/power percentage lookup table we might get quite good estimation of wind power for each hour.
> 
> Not a clue if this would work but just as an idea.
> 
> Data itself looks like free to use (ref https://www.arcgis.com/home/item.html?id=b7befefe269b4932a37160a1fea26640). Seems that there is also monthly updates to the list (when listing features by author).

This is good to know. It's still quite a leap to start aggregating and cross-correlating this with weather data to develop a wind power function, index or model out of it.

Given that in the end the wind power forecast would necessarily be largely a function of wind input (right?), I wonder if adding that extra layer adds signal or noise. What if the model is given wind as input to start with, and so it has one less step of "reasoning" to find its correlation to price?

I don't know the answer to that. It could, but only if the wind power model is actually good, on par with what Foreca does. Based on initial numbers the current plan b is already pretty decent. Next few days will shed more light on that.

**Comment by savikko** [comment]
> This is good to know. It's still quite a leap to start aggregating and cross-correlating this with weather data to develop a wind power function, index or model out of it.

Actually, reading few papers about it, it looks to be quite simple (ref e.g. https://www.theseus.fi/bitstream/handle/10024/754476/Apilisto_Janne.pdf?sequence=3 pages 14-22). Or at least it should be quite good approximate, something like this:

```
def turbine_efficiency(wind_speed):
    if wind_speed < 4:
        return 0
    elif 4 <= wind_speed < 8:
        # Linear increase from 0% to 100% as wind speed goes from 4 m/s to 8 m/s
        return (wind_speed - 4) / (8 - 4) * 100
    elif 8 <= wind_speed <= 25:
        return 100
    else:
        # Wind speed above 25 m/s
        return 0
```

But it is probably also the wind direction which affects to this power (basically might be something like just extra factor (wind from east is probably always better [factor of 1] and then western winds may have some 0.5 or so factor).

> Given that in the end the wind power forecast would necessarily be largely a function of wind input (right?), I wonder if adding that extra layer adds signal or noise. What if the model is given wind as input to start with, and so it has one less step of "reasoning" to find its correlation to price?
> 
> I don't know the answer to that. It could, but only if the wind power model is actually good, on par with what Foreca does. Based on initial numbers the current plan b is already pretty decent. Next few days will shed more light on that.

Thats totally true. I also do not have any clue how much winds really differ between wind turbine areas.

Anyway, this model could be at least interesting to try out, although not sure if it has any significant effect on this.

**Comment by oh4kpn** [comment]
requirements.txt needs probably lxml

**Comment by vividfog** [comment]
> requirements.txt needs probably lxml

Thanks, noticed that too. I'm currently deploying this on an old MacBook Air which shall serve as the sähkövatkain source server. While doing that, I found a silly bug in the prediction data frame construction. I wouldn't recommend anyone using this code until this issue is marked as closed. Very interesting bookmarks for future reference in here though.

**Comment by T3m3z** [comment]
One possible enhancement popped into my mind at 2AM: wind speeds are instantaneous (wind power production one day ago does not affect production today) but on the load side it might (not sure but just thinking) beneficial to give the model some information about the past temperatures too.

My logic here is that for wooden houses the energy needs are instantaneous but massive apartment blocks made from concrete store heat energy into their "structural reservoir". That might create some offset on the load side which depends on how long the low temperates have been around.

https://tekniikanmaailma.fi/kun-pitka-sahkokatko-iskee-puutalo-kylmenee-alle-vuorokaudessa-nain-puolustusministerio-neuvoo-toimimaan-pitkan-sahkokatkon-aikana/

Not the best analysis but maybe this picture shows that there might be something behind this:
![image](https://github.com/vividfog/nordpool-predict-fi/assets/6449536/9e87efcb-7708-461d-a1ad-ba3bd69c3e7c)

Data from Fingrid (https://data.fingrid.fi/data?datasets=124) and FMI (https://en.ilmatieteenlaitos.fi/download-observations). Electricity consumption starts slowly to increase after temperatures in Helsinki dropped significantly at the end of last December. Electricity consumption seems to level of roughly 3-4 days later.

**Comment by sjksp** [comment]
@T3m3z
And also past temperature and wind will correlate with district heating energy storage behaviour. Energy storages will delay the reaction in price when weather changes.

**Comment by vividfog** [comment]
This would then make it a time series job. I don't yet know how to formulate that into a Random Forest data set. Something about "Lagged Variables". 

It's technically possible to create an ensemble out of many models, perhaps throwing the whole challenge to Autogen might produce something to lean back and look at. It's pretty good at spitballing implementation ideas and also executing on them for initial results. For example by dropping the full database CSV for it and promoting to work out a hypothesis implementation. But it needs a fantastic job description to be effective. 

I think that for short term I'll make the code more robust and improve the evals to establish a baseline of how well the current model works. Otherwise it's hard to say if it has improved when a new idea is implemented.

**Comment by Maaxion** [comment]
AFAIK those windforecasts are for 2m elevation, most new windmills are higher up.

If you want to use wind forecast as a proxy for wind power produced, it might be beneficial to choose weather forecast locations close to the larger known wind mill parks. Ideally you'd want to weight the wind forecast with the potential power produced at it's location to get it to more accurately reflect power production.

**Comment by Cuzzie** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Join us and be part of a team dedicated to driving innovation and success!

## How to Apply:
To apply for this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.thinking-and-coding, @sevensinjai, @dantodor, @mostafaahmed1000, @B3ns44d, @smalltigerlee, @CosmoAbdon, @chaosbus, @carlxx02, @Neerajjr11, @Kreshnik, @skyline75489, @JasonSanYe, @Dank-back, @god0000, @lalitpagaria, @rajephon, @BeiXiao, @xuedierhuo, @oogxdd

**Comment by vividfog** [comment]
Closing this for now. FMI integration was already done. The wind speed is observed and forecast at 10 meters. To avoid stacking models, these weather stations provide direct observations and direct forecasts for the same point, versus using a grid interpolation. I'm not aware of weather stations nearby enough that provide 100 m observations and forecasts at the same location directly.

Other ideas introduced here are interesting and I'd really like to revisit them in the future. The new snapshot system, once continuous training has been running for a while and the snapshots stabilize (if they do), should provide a better idea of what scenarios are currently difficult and would benefit most from new data sources.

There's a separate issue and a PR about nuclear power predictions based on market messages, and that'll become part of the repo as soon as I have some free time again to integrate it into the pipeline.
